[Unit]
Conflicts=getty@tty1.service
Wants=seatd.service dbus.socket
After=systemd-user-sessions.service systemd-logind.service seatd.service dbus.socket

[Service]
TTYPath=/dev/tty1
StandardInput=tty
StandardOutput=journal+console
StandardError=journal+console
