minimumIconSize=34
maximumIconSize=60
spacingFactor=0.50
showTooltip=true
tooltipFontSize=11
panelStyle=6
floatingMargin=7
bouncingLauncherIcon=true
zoomingAnimationSpeed=16
backgroundColor=#cc0c1017
backgroundColor2D=#cc0c1017
backgroundColorMetal2D=#cc0c1017
borderColor=#ecb860
borderColorMetal2D=#ecb860
activeIndicatorColor=#ecb860
activeIndicatorColor2D=#ecb860
activeIndicatorColorMetal2D=#ecb860
inactiveIndicatorColor=#94d2bd
inactiveIndicatorColor2D=#94d2bd
inactiveIndicatorColorMetal2D=#94d2bd
firstRunMultiScreen=false
firstRunWindowCountIndicator=false

[Application Menu]
label=Apps
iconSize=30
fontSize=13
backgroundAlpha=0.9

[TaskManager]
currentDesktopTasksOnly=false
currentScreenTasksOnly=true
groupTasksByApplication=true
showOnlyMinimized=false

[VolumeControl]
volumeScrollStep=5

[Clock]
use24HourClock=true
fontScaleFactor=0.84
