position=1
screen=0
visibility=0
autoHide=false
showApplicationMenu=false
showPager=false
showTaskManager=true
showTrash=true
showWifiManager=false
showVolumeControl=true
showBatteryIndicator=true
showKeyboardLayout=false
showVersionChecker=false
showClock=true
launchers=show-desktop;foot;thunar;wofi;separator;lock-screen;log-out;separator
