[Unit]
After=graphical-session.target labwc-session.target
PartOf=graphical-session.target labwc-session.target

[Service]
ExecCondition=/usr/bin/systemctl --user --quiet is-active graphical-session.target
Environment=QT_NO_XDG_DESKTOP_PORTAL=1
