#!/bin/sh
# Shared F2FS-family late_command implementation. This file is sourced.

run_f2fs_family_late_command() {
requested_seed_base=${1:-}
requested_host_profile=${2:-}
HOOK_FAMILY=f2fs

late_command_shared_init "$requested_seed_base" "$requested_host_profile" "$HOOK_FAMILY"

late_command_fetch_common_assets "$(installer_repo_join_var DIR_SCRIPTS_RUNTIME f2fs.sh)"
fetch_hook "$(installer_repo_join_var DIR_HOOKS_SHARED_TARGET etc/default/grub-profiles.tmpl)" "$TMP_ENV_DIR/grub-profiles"
late_command_load_runtime_env false
if [ "${DUALBOOT_ENABLED:-false}" = "true" ]; then
  fatal "dualboot runtime state is invalid for F2FS layouts"
fi
late_command_load_host_env
install_target_preseed_runtime_defaults
install_target_wpa_supplicant_runtime_policy
late_command_require_class_policy_env
installer_ensure_context_loaded "${SEED_BASE:-}"
CPU_CLASS=$(installer_selected_class_for_purpose cpu 2>/dev/null || printf '%s' "${INSTALLER_CPU_CLASS:-}")
DISK_CLASS=$(installer_selected_class_for_purpose storage 2>/dev/null || printf '%s' "${INSTALLER_DISK_CLASS:-}")
GPU_CLASSES=$(installer_selected_class_for_purpose gpu 2>/dev/null || printf '%s' "${INSTALLER_GPU_CLASS:-}")
DISK_HOOK_ROOT=$(installer_repo_join_var DIR_HOOKS_HARDWARE_DISK "${DISK_CLASS}")
CPU_HOOK_ROOT=$(installer_repo_join_var DIR_HOOKS_HARDWARE_CPU "${CPU_CLASS}")
NVIDIA_ADDON_SELECTED=false
NVIDIA_GPU_DETECTED=false
PODMAN_ADDON_SELECTED=false
if installer_selected_class_reference_is_selected addon/nvidia; then
  NVIDIA_ADDON_SELECTED=true
fi
PODMAN_ADDON_SELECTED=$(podman_addon_selection_state)
if installer_nvidia_gpu_detected; then
  NVIDIA_GPU_DETECTED=true
fi
if [ "$NVIDIA_ADDON_SELECTED" = true ] && [ "$NVIDIA_GPU_DETECTED" != true ]; then
  warn "addon/nvidia was selected but no NVIDIA PCI display adapter was detected; NVIDIA target packages and modprobe config stay disabled"
fi
info "late installer context: host_profile=${INSTALLER_HOST_PROFILE:-unset} selected_groups=${INSTALLER_SELECTED_GROUPS:-unset} selected_classes=${INSTALLER_SELECTED_CLASSES:-unset} cpu=${CPU_CLASS:-unset} disk=${DISK_CLASS:-unset} gpu=${GPU_CLASSES:-none} nvidia_addon=${NVIDIA_ADDON_SELECTED} nvidia_gpu=${NVIDIA_GPU_DETECTED} podman_addon=${PODMAN_ADDON_SELECTED}"

default_file_modprobe_mei_blacklist=$FILE_MODPROBE_MEI_BLACKLIST
default_file_modprobe_nvidia=$FILE_MODPROBE_NVIDIA
default_file_modprobe_usbcore=$FILE_MODPROBE_USBCORE
default_file_modprobe_cfg80211=$FILE_MODPROBE_CFG80211
default_file_modprobe_nvme_blacklist=$FILE_MODPROBE_NVME_BLACKLIST
default_file_modules_load_emmc_storage=$FILE_MODULES_LOAD_EMMC_STORAGE

target_enable_mei_blacklist=false
target_enable_nvidia=false
target_enable_nvme_tunables=false
target_enable_emmc_storage=false

case "${CPU_CLASS:-intel}" in
  amd)
    ;;
  intel)
    target_enable_mei_blacklist=true
    ;;
  *)
    fatal "unsupported CPU class: ${CPU_CLASS:-unset}"
    ;;
esac

case "${DISK_CLASS:-emmc}" in
  emmc)
    target_enable_emmc_storage=true
    ;;
  *)
    fatal "unsupported F2FS disk class: ${DISK_CLASS:-unset}"
    ;;
esac

if [ "$NVIDIA_ADDON_SELECTED" = true ] && [ "$NVIDIA_GPU_DETECTED" = true ]; then
  target_enable_nvidia=true
fi

GRAPHICS_INITRAMFS_MODULES=$(late_command_graphics_initramfs_modules "$GPU_CLASSES" "$target_enable_nvidia")

set_optional_path FILE_MODPROBE_MEI_BLACKLIST "$target_enable_mei_blacklist" "$default_file_modprobe_mei_blacklist"
FILE_MODPROBE_NVIDIA=$default_file_modprobe_nvidia
set_optional_path FILE_MODPROBE_USBCORE "$target_enable_nvme_tunables" "$default_file_modprobe_usbcore"
set_optional_path FILE_MODPROBE_CFG80211 false "$default_file_modprobe_cfg80211"
set_optional_path FILE_MODPROBE_NVME_BLACKLIST "$target_enable_nvme_tunables" "$default_file_modprobe_nvme_blacklist"
set_optional_path FILE_MODULES_LOAD_EMMC_STORAGE "$target_enable_emmc_storage" "$default_file_modules_load_emmc_storage"

GRAPHICS_INITRAMFS_MODULES=$(module_value_to_lines "${GRAPHICS_INITRAMFS_MODULES:-}")

runtime_apply_ssh_from_classes

write_target_fstab() {
  # Runtime layout env fragments provide the device paths and mount options used here.
  # shellcheck disable=SC2153
  root_src=$(device_source "${DEV_PART_ROOT}")
  # shellcheck disable=SC2153
  boot_src=$(device_source "${DEV_PART_BOOT}")
  efi_src=$(device_source "${DEV_PART_EFI}")
  journal_src=$(device_source "${DEV_PART_VAR_LOG_JOURNAL}")

  {
    printf '# Generated by installer automation late_command\n\n'
    printf '# Pseudo filesystems\n'
    fstab_entry proc /proc proc defaults 0 0
    printf '\n# Boot partitions\n'
    # shellcheck disable=SC2153
    fstab_entry "$boot_src" "$DIR_BOOT" ext4 "$MNT_BOOT_OPTS" 0 2
    fstab_entry "$efi_src" "$DIR_BOOT_EFI" vfat "$MNT_EFI_OPTS" 0 2
    printf '\n# Core filesystems\n'
    # shellcheck disable=SC2153
    fstab_entry "$root_src" / f2fs "$MNT_F2FS_ROOT_OPTS" 0 1
    if [ -n "${DEV_PART_HOME:-}" ] && [ "${DEV_PART_HOME_MB:-0}" -gt 0 ]; then
      home_src=$(device_source "$DEV_PART_HOME")
      fstab_entry "$home_src" "$DIR_HOME" f2fs "$MNT_F2FS_HOME_OPTS" 0 2
    fi
    if [ -n "${DEV_PART_POOL:-}" ] && [ "$DEV_PART_POOL_MB" -gt 0 ]; then
      pool_src=$(device_source "$DEV_PART_POOL")
      fstab_entry "$pool_src" "$DIR_POOL" ext4 "$MNT_EXT4_POOL_OPTS" 0 2
    fi
    if tmpfs_policy_enabled TMPFS_DATA_RUN; then
      printf '\n# Data runtime tmpfs\n'
      fstab_entry tmpfs "$DIR_DATA_RUN" tmpfs "$MNT_DATA_RUN_TMPFS_OPTS" 0 0
    fi
    printf '\n# Volatile tmpfs trees\n'
    if tmpfs_policy_enabled TMPFS_VAR_LOG; then
      fstab_entry tmpfs "$DIR_VAR_LOG" tmpfs "$MNT_VAR_LOG_TMPFS_OPTS" 0 0
    fi
    if tmpfs_policy_enabled TMPFS_VAR_CACHE; then
      fstab_entry tmpfs "$DIR_VAR_CACHE" tmpfs "$MNT_VAR_CACHE_TMPFS_OPTS" 0 0
    fi
    if tmpfs_policy_enabled TMPFS_VAR_LIB_APT_LISTS; then
      fstab_entry tmpfs "$DIR_APT_LISTS" tmpfs "$MNT_APT_LISTS_TMPFS_OPTS" 0 0
    fi
    if tmpfs_policy_enabled TMPFS_SYSTEMD_COREDUMP; then
      fstab_entry tmpfs "$DIR_SYSTEMD_COREDUMP" tmpfs "$MNT_COREDUMP_TMPFS_OPTS" 0 0
    fi
    fstab_entry tmpfs "$DIR_TMP" tmpfs "$MNT_TMP_OPTS" 0 0
    if tmpfs_policy_enabled TMPFS_DEV_SHM; then
      fstab_entry tmpfs "$DIR_DEV_SHM" tmpfs "$MNT_DEV_SHM_OPTS" 0 0
    fi
    printf '\n# Persistent journal\n'
    fstab_entry "$journal_src" "$DIR_VAR_LOG_JOURNAL" ext4 "$MNT_VAR_LOG_JOURNAL_OPTS" 0 2
  } | write_target_file /etc/fstab 0644
  cp /target/etc/fstab /target/etc/fstab.layout-cache 2>/dev/null || true
  cp /target/etc/fstab /target/etc/fstab.orig 2>/dev/null || true
}

prepare_target_deferred_tmpfs_roots() {
  journal_mount="/target${DIR_VAR_LOG_JOURNAL}"

  if tmpfs_policy_enabled TMPFS_VAR_LOG &&
    target_mount_source "$journal_mount" >/dev/null 2>&1; then
    info "unmounting ${journal_mount} so the installed system remounts the persistent journal cleanly on reboot"
    umount "$journal_mount" || {
      fatal "failed to unmount ${journal_mount} while preparing deferred tmpfs roots"
    }
  fi

  rmdir "$journal_mount" 2>/dev/null || true
}

write_target_kernel_tunables() {
  stage_target_asset_if_path "${DISK_HOOK_ROOT}/target/etc/modprobe.d/nvme-blacklist.conf" "${FILE_MODPROBE_NVME_BLACKLIST:-}" "${DIR_MODPROBE_D}/nvme-blacklist.conf" 0644
  stage_target_asset_if_path "${CPU_HOOK_ROOT}/target/etc/modprobe.d/05-mei-blacklist.conf" "${FILE_MODPROBE_MEI_BLACKLIST:-}" "${DIR_MODPROBE_D}/05-mei-blacklist.conf" 0644
  if [ "$target_enable_nvidia" = true ]; then
    stage_target_asset "$(installer_repo_join_var DIR_HOOKS_HARDWARE_GPU nvidia/target/etc/modprobe.d/nvidia.conf)" "${FILE_MODPROBE_NVIDIA}" 0644
  else
    stage_target_asset "$(installer_repo_join_var DIR_HOOKS_HARDWARE_BLACKLIST nvidia.conf)" "${FILE_MODPROBE_NVIDIA}" 0644
  fi
  stage_target_asset_if_path "${DISK_HOOK_ROOT}/target/etc/modprobe.d/usbcore.conf" "${FILE_MODPROBE_USBCORE:-}" "${DIR_MODPROBE_D}/usbcore.conf" 0644
  stage_target_asset_if_path "${CPU_HOOK_ROOT}/target/etc/modprobe.d/cfg80211.conf" "${FILE_MODPROBE_CFG80211:-}" "${DIR_MODPROBE_D}/cfg80211.conf" 0644
  stage_target_asset_if_path "${DISK_HOOK_ROOT}/target/etc/modules-load.d/20-emmc-storage.conf" "${FILE_MODULES_LOAD_EMMC_STORAGE:-}" "${DIR_MODULES_LOAD}/20-emmc-storage.conf" 0644
  stage_target_asset "$(installer_repo_join_var DIR_HOOKS_SHARED_TARGET etc/modules-load.d/30-storage-memory.conf)" "${FILE_MODULES_LOAD_STORAGE_MEMORY}" 0644
  stage_target_asset "$(installer_repo_join_var DIR_HOOKS_SHARED_TARGET etc/modules-load.d/32-tpm.conf)" "${FILE_MODULES_LOAD_TPM}" 0644
  stage_target_asset "$(installer_repo_join_var DIR_HOOKS_SHARED_TARGET etc/sysctl.d/10-baseline.conf)" "${FILE_SYSCTL_BASELINE}" 0644
  stage_target_asset "$(installer_repo_join_var DIR_HOOKS_SHARED_TARGET etc/sysctl.d/20-storage-memory.conf)" "${FILE_SYSCTL_STORAGE_MEMORY}" 0644
  render_target_asset "$(installer_repo_join_var DIR_HOOKS_SHARED_TARGET etc/sysctl.d/25-storage-static.conf.tmpl)" "${FILE_SYSCTL_FAMILY_OVERRIDE}" 0644
  stage_target_asset "$(installer_repo_join_var DIR_HOOKS_SHARED_TARGET etc/sysctl.d/profiles/balanced/40-balanced.conf)" "${FILE_SYSCTL_PROFILE_DEFAULT}" 0644
  render_target_asset "$(installer_repo_join_var DIR_HOOKS_SHARED_TARGET etc/sysctl.d/profiles/balanced/50-storage-balanced.conf.tmpl)" "${FILE_SYSCTL_PROFILE_DEFAULT_FAMILY_OVERRIDE}" 0644
  stage_target_asset "$(installer_repo_join_var DIR_HOOKS_SHARED_TARGET etc/sysctl.d/profiles/hardened/40-hardened.conf)" "${FILE_SYSCTL_PROFILE_HARDENED}" 0644
  render_target_asset "$(installer_repo_join_var DIR_HOOKS_SHARED_TARGET etc/sysctl.d/profiles/hardened/50-storage-hardened.conf.tmpl)" "${FILE_SYSCTL_PROFILE_HARDENED_FAMILY_OVERRIDE}" 0644
  stage_target_asset "$(installer_repo_join_var DIR_HOOKS_SHARED_TARGET etc/sysctl.d/profiles/performance/40-performance.conf)" "${FILE_SYSCTL_PROFILE_PERFORMANCE}" 0644
  render_target_asset "$(installer_repo_join_var DIR_HOOKS_SHARED_TARGET etc/sysctl.d/profiles/performance/50-storage-performance.conf.tmpl)" "${FILE_SYSCTL_PROFILE_PERFORMANCE_FAMILY_OVERRIDE}" 0644

  stage_target_asset "$(installer_repo_join_var DIR_HOOKS_SHARED_TARGET etc/initramfs-tools/conf.d/99-compress.conf)" "${FILE_INITRAMFS_CUSTOM_CONF}" 0644
  stage_target_asset "$(installer_repo_join_var DIR_HOOKS_SHARED_TARGET etc/initramfs-tools/conf.d/resume)" "${FILE_INITRAMFS_RESUME}" 0644
  stage_target_asset "$(installer_repo_join_var DIR_HOOKS_SHARED_TARGET etc/initramfs-tools/scripts/local-premount/20-btrfs-root-no-fsck)" "/etc/initramfs-tools/scripts/local-premount/20-btrfs-root-no-fsck" 0755
  render_target_asset "${DISK_HOOK_ROOT}/target/etc/initramfs-tools/modules.tmpl" "${FILE_INITRAMFS_MODULES}" 0644

  install_target_bootprofile_assets

  stage_target_zram_assets
  write_target_swap_fallback_config
  stage_target_asset "$(installer_repo_join_var DIR_HOOKS_SHARED_TARGET usr/local/sbin/swap-fallback-setup.tmpl)" "${FILE_SWAP_FALLBACK_HELPER}" 0755
  render_target_template "$TMP_ENV_DIR/swap-fallback.service.tmpl" "/target${FILE_SWAP_FALLBACK_SERVICE}" 0644

  stage_target_common_storage_maintenance_assets
}

verify_target_swap_fallback_staging() {
  # shellcheck disable=SC2016
  run_in_target "verify staged swap fallback payload" /bin/sh -c '
set -eu
config=$1
helper=$2
service=$3

[ -r "$config" ]
[ -x "$helper" ]
[ -r "$service" ]
[ -L /etc/systemd/system/multi-user.target.wants/swap-fallback.service ]
' sh \
  "${FILE_SWAP_FALLBACK_CONFIG}" \
  "${FILE_SWAP_FALLBACK_HELPER}" \
  "${FILE_SWAP_FALLBACK_SERVICE}"
}

verify_target_storage_maintenance_staging() {
  verify_target_tmpfs_pre_clean_and_apt_refresh_staging
}

verify_target_graphics_staging() {
  # shellcheck disable=SC2016
run_in_target "verify staged graphics payload" /bin/sh -c '
set -eu
initramfs_modules=$1
nvidia_modprobe=$2

[ -r "$initramfs_modules" ]
[ -r "$nvidia_modprobe" ]
' sh \
  "${FILE_INITRAMFS_MODULES}" \
  "${DIR_MODPROBE_D}/nvidia.conf"
}

verify_target_platform_tunables_staging() {
  # shellcheck disable=SC2016
  run_in_target "verify staged platform tunables" /bin/sh -c '
set -eu
cfg80211_file=$1
usbcore_file=$2
nvme_blacklist_file=$3
mei_blacklist_file=$4
emmc_storage_file=$5

if [ -n "$cfg80211_file" ]; then [ -r "$cfg80211_file" ]; fi
if [ -n "$usbcore_file" ]; then [ -r "$usbcore_file" ]; fi
if [ -n "$nvme_blacklist_file" ]; then [ -r "$nvme_blacklist_file" ]; fi
if [ -n "$mei_blacklist_file" ]; then [ -r "$mei_blacklist_file" ]; fi
if [ -n "$emmc_storage_file" ]; then [ -r "$emmc_storage_file" ]; fi
' sh \
  "${FILE_MODPROBE_CFG80211:-}" \
  "${FILE_MODPROBE_USBCORE:-}" \
  "${FILE_MODPROBE_NVME_BLACKLIST:-}" \
  "${FILE_MODPROBE_MEI_BLACKLIST:-}" \
  "${FILE_MODULES_LOAD_EMMC_STORAGE:-}"
}

verify_target_sysctl_staging() {
  # shellcheck disable=SC2016
  run_in_target "verify staged sysctl payload" /bin/sh -c '
set -eu
sysctl_base=$1
sysctl_storage=$2
sysctl_family=$3
sysctl_default=$4
sysctl_default_family=$5
sysctl_hardened=$6
sysctl_hardened_family=$7
sysctl_performance=$8
sysctl_performance_family=$9

[ -r "$sysctl_base" ]
[ -r "$sysctl_storage" ]
[ -r "$sysctl_family" ]
[ -r "$sysctl_default" ]
[ -r "$sysctl_default_family" ]
[ -r "$sysctl_hardened" ]
[ -r "$sysctl_hardened_family" ]
[ -r "$sysctl_performance" ]
[ -r "$sysctl_performance_family" ]
' sh \
  "${FILE_SYSCTL_BASELINE}" \
  "${FILE_SYSCTL_STORAGE_MEMORY}" \
  "${FILE_SYSCTL_FAMILY_OVERRIDE}" \
  "${FILE_SYSCTL_PROFILE_DEFAULT}" \
  "${FILE_SYSCTL_PROFILE_DEFAULT_FAMILY_OVERRIDE}" \
  "${FILE_SYSCTL_PROFILE_HARDENED}" \
  "${FILE_SYSCTL_PROFILE_HARDENED_FAMILY_OVERRIDE}" \
  "${FILE_SYSCTL_PROFILE_PERFORMANCE}" \
  "${FILE_SYSCTL_PROFILE_PERFORMANCE_FAMILY_OVERRIDE}"
}

write_target_fstab
ensure_target_managed_runtime_storage_roots
provision_target_identity
stage_target_account_shell_assets
ensure_target_account_home_ownership
install_target_account_shell_assets
install_target_account_sudoers
configure_target_usb_media_access
write_target_grub_dropins
set_target_grub_default_entry
ensure_target_secure_boot_state_mount
write_target_secure_boot_payloads
remove_target_secure_boot_crypttab_entry
install_target_secure_boot_kernel_hooks
repair_target_pkgsel_include_packages
verify_target_pkgsel_include_packages
stage_target_xssh_helpers
configure_target_rootless_podman_if_selected
configure_target_gitlab_runner_if_selected
sanitize_target_xfs_scrub_systemd_units
install_target_wpa_supplicant_runtime_policy
write_target_kernel_tunables
ensure_target_secure_boot_packages
provision_target_ssh_server
install_target_preseed_network_handoff
configure_target_apparmor_auditd
dedupe_target_tmpfiles_legacy_lock
prepare_target_secure_boot_runtime
install_target_firstboot_logger
enable_target_storage_units
set_target_default_unit
verify_target_swap_fallback_staging
verify_target_zram_staging
verify_target_storage_maintenance_staging
verify_target_xfs_scrub_systemd_units
verify_target_graphics_staging
verify_target_platform_tunables_staging
verify_target_bootprofile_core_staging
verify_target_sysctl_staging
verify_target_secure_boot_staging
disable_stock_kernel_menu

if command -v in-target >/dev/null 2>&1; then
  load_target_boot_tool_state
  if [ "${TARGET_HAS_UPDATE_INITRAMFS}" = 1 ]; then
    run_in_target "update initramfs" /usr/sbin/update-initramfs -u -k all
  fi
  sign_target_installed_kernel_modules
  require_target_grub_installed
  install_target_grub_profiles
  run_target_grub_config_update
  repair_target_installed_kernels
  verify_target_signed_kernel_images
  queue_target_secure_boot_mok_import
  close_target_secure_boot_state
fi

verify_grub_profile_entries
configure_target_dbus_broker
prepare_target_deferred_tmpfs_roots
prepare_target_volatile_mountpoints_for_first_boot
installer_archive_logs_to_target copy || true
}
