#!/bin/sh
set -e

if command -v systemd-tmpfiles >/dev/null 2>&1; then
    systemd-tmpfiles --create /etc/tmpfiles.d/zram-writeback.conf || true
fi
if command -v systemctl >/dev/null 2>&1; then
    systemctl daemon-reload || true
fi

#DEBHELPER#
exit 0
